# # sub_agents/planner/agent.py

# from google.adk.agents import Agent
# from google.adk.tools.agent_tool import AgentTool
# # Ensure relative paths are correct
# from ..data_collector.agent import data_collector_agent
# from ..consolidated_writer.agent import consolidated_writer_agent 

# stock_analysis_planner = Agent(
#     name="stock_analysis_planner",
#     model="gemini-2.0-flash",
#     description="Orchestrates the 2-step workflow: get data, then write report.",
#     instruction="""
#     You are a stock analysis report planner.
#     Your task is to generate a report by calling a sequence of agents.
#     You must call them in this exact order:

#     1.  `data_collector_agent` (To get all financial data)
#     2.  `consolidated_writer_agent` (To analyze all data and write the final report)

#     CRITICAL RULE: Your final response must be *the verbatim output* from the 
#     `consolidated_writer_agent`. Do not add any conversational text, summaries, 
#     preliminary greetings, or introductory phrases (like "Here is a stock analysis..."). 
#     Your output MUST START directly with the Markdown heading: '## Stock Analysis Report: [Ticker]'.
#     """,
#     tools=[
#         AgentTool(data_collector_agent),
#         AgentTool(consolidated_writer_agent),
#     ],
# )

# sub_agents/planner/agent.py

from google.adk.agents import Agent
from google.adk.tools.agent_tool import AgentTool

from ..data_collector.agent import data_collector_agent
from ..fundamental.agent import fundamental_analysis_agent
from ..valuation.agent import valuation_analysis_agent
from ..risks.agent import risk_analysis_agent
from ..aggregator.agent import aggregator_agent


stock_analysis_planner = Agent(
    name="stock_analysis_planner",
    model="gemini-2.0-flash",
    description=(
        "Orchestrates a multi-step workflow for stock analysis: "
        "collect data, run fundamental/valuation/risk analysts, then aggregate "
        "into a final Markdown report."
    ),
    instruction="""
You are the planning and orchestration agent for the Stock Insight system.

Your job is to:
1. Interpret the user's query and extract the target ticker (or company name).
2. Call the appropriate sub-agents in the **correct order**.
3. Ensure the final answer to the user is the Markdown report generated by `aggregator_agent`.

You must follow this workflow:

STEP 1 — Data Collection
- Call `data_collector_agent` **exactly once**.
- If the JSON from data_collector_agent contains a field "status" that is not "success",
  you MUST stop the workflow and return an error message to the user instead of continuing.
  In that case, respond with a short Markdown message starting with:
  "## Stock Analysis Error"
  and include the error_message from the JSON.

STEP 2 — Analysis Agents
- Assuming data collection succeeded, you now have access to the JSON with:
  - ticker
  - current_price
  - metrics
  - headlines
- Use this JSON as the basis to call the following analysis agents:
  1) `fundamental_analysis_agent`
  2) `valuation_analysis_agent`
  3) `risk_analysis_agent`
- Each of these tools expects the JSON or the relevant subset (ticker + metrics + headlines).
- They will each return a small JSON with one field:
  - {"fundamental_analysis": "..."}
  - {"valuation_analysis": "..."}
  - {"risk_analysis": "..."}

STEP 3 — Aggregation
- After you have the outputs from all three analysis agents,
  call `aggregator_agent` **exactly once**.
- Provide aggregator_agent with enough context so it can:
  - read ticker and current_price from data_collector_agent output
  - read the three analysis strings from the other agents
- aggregator_agent will then produce the final Markdown report.

CRITICAL OUTPUT RULE:
- Your final response to the user MUST be the **exact** Markdown output from `aggregator_agent`.
- Do NOT wrap it in JSON.
- Do NOT add any extra commentary, explanations, or text before or after it.
- Do NOT restate the content yourself.

You are allowed to think step-by-step internally, but every tool call must be explicit.
    """,
    tools=[
        AgentTool(data_collector_agent),
        AgentTool(fundamental_analysis_agent),
        AgentTool(valuation_analysis_agent),
        AgentTool(risk_analysis_agent),
        AgentTool(aggregator_agent),
    ],
)
